/* =======================================================================
   単語帳データ（102）
   -----------------------------------------------------------------------
   書き方は exams/101/cards.js と同じ。102 のカードは ID 2001 から振る。
   ======================================================================= */

addCards([

  /* ===== 1.06 エイリアス・設定ファイル・関数 ===== */
  { id: 2001, sec: "1.06/エイリアス（alias）", term: "alias 名前='コマンド'", mean: "エイリアス（別名）を設定する。= の前後にスペースを入れない。引数なしで一覧表示" },
  { id: 2002, sec: "1.06/エイリアス（alias）", term: "unalias", mean: "エイリアスを解除する。-a ですべて解除" },
  { id: 2003, sec: "1.06/エイリアス（alias）", term: "\\コマンド", mean: "先頭に \\ を付けると、エイリアスを無視して本来のコマンドを実行する" },
  { id: 2004, sec: "1.06/bashの設定ファイル", term: "/etc/profile", mean: "ログイン時に全ユーザー共通で読まれる設定ファイル" },
  { id: 2005, sec: "1.06/bashの設定ファイル", term: "~/.bash_profile", mean: "ログイン時にそのユーザーだけが読む。無ければ ~/.bash_login → ~/.profile の順に探す" },
  { id: 2006, sec: "1.06/bashの設定ファイル", term: "~/.bashrc", mean: "bash を起動するたびに読まれる。エイリアスや関数を書く" },
  { id: 2007, sec: "1.06/bashの設定ファイル", term: "~/.bash_logout", mean: "ログアウト時に読まれる" },
  { id: 2008, sec: "1.06/bashの設定ファイル", term: "source ファイル（. ファイル）", mean: "ファイルを今のシェルで実行する。設定の変更をすぐ反映できる" },
  { id: 2009, sec: "1.06/シェル関数", term: "function 名前() { コマンド; }", mean: "シェル関数を定義する。中では $1 $2 で引数を受け取る" },
  { id: 2010, sec: "1.06/シェル関数", term: "declare -f 関数名", mean: "定義した関数の内容を表示する（-F は名前だけ）" },
  { id: 2011, sec: "1.06/シェル関数", term: "unset 関数名", mean: "シェル関数を削除する（変数の削除と同じ）" },

  /* ===== 1.06 シェルスクリプト ===== */
  { id: 2012, sec: "1.06/シェルスクリプトの実行方法", term: "#!/bin/bash（シバン）", mean: "スクリプトの1行目。./スクリプト で実行したときに使うインタプリタを指定する" },
  { id: 2013, sec: "1.06/シェルスクリプトの実行方法", term: "bash script ／ ./script", mean: "新しいシェル（子プロセス）で実行する。./ の形は実行権が必要" },
  { id: 2014, sec: "1.06/シェルスクリプトの実行方法", term: "bash -x script", mean: "実行するコマンドを1行ずつ表示しながら動かす（デバッグ用）" },
  { id: 2015, sec: "1.06/特殊変数と引数（$1・$#・shift）", term: "$0", mean: "スクリプト自身の名前" },
  { id: 2016, sec: "1.06/特殊変数と引数（$1・$#・shift）", term: "$#", mean: "引数の個数" },
  { id: 2017, sec: "1.06/特殊変数と引数（$1・$#・shift）", term: "$?", mean: "直前のコマンドの終了ステータス（0＝成功）" },
  { id: 2018, sec: "1.06/特殊変数と引数（$1・$#・shift）", term: "$* ／ $@", mean: "すべての引数（\"$@\" は1つずつ別々に扱う）" },
  { id: 2019, sec: "1.06/特殊変数と引数（$1・$#・shift）", term: "shift", mean: "引数を1つずつ前へずらす（$2 が $1 に。$# が1減る）" },
  { id: 2020, sec: "1.06/条件式（test と [ ]）", term: "-eq / -ne / -gt / -ge / -lt / -le", mean: "数値の比較：等しい／等しくない／大きい／以上／小さい／以下" },
  { id: 2021, sec: "1.06/条件式（test と [ ]）", term: "-f / -d / -e", mean: "ファイルの判定：通常ファイル／ディレクトリ／存在する" },
  { id: 2022, sec: "1.06/条件式（test と [ ]）", term: "-z / -n", mean: "文字列が空（zero）／空でない（nonzero）" },
  { id: 2023, sec: "1.06/条件式（test と [ ]）", term: "[ 条件 ]", mean: "test コマンドの別の書き方。[ の後と ] の前にスペースが必須" },
  { id: 2024, sec: "1.06/制御構造（if・case・for・while）", term: "if 〜 fi", mean: "条件分岐。then の前に ; か改行、終わりは fi" },
  { id: 2025, sec: "1.06/制御構造（if・case・for・while）", term: "case 〜 esac", mean: "値による分岐。各パターンは ;; で終え、全体を esac で閉じる" },
  { id: 2026, sec: "1.06/制御構造（if・case・for・while）", term: "for 変数 in 値… do 〜 done", mean: "値の数だけ繰り返す" },
  { id: 2027, sec: "1.06/制御構造（if・case・for・while）", term: "while ⇔ until", mean: "条件が真の間くり返す ⇔ 偽の間くり返す" },
  { id: 2028, sec: "1.06/スクリプトで使う小技（read・seq・exit・終了ステータス）", term: "read 変数", mean: "標準入力から1行読んで変数に入れる（-p でプロンプト表示）" },
  { id: 2029, sec: "1.06/スクリプトで使う小技（read・seq・exit・終了ステータス）", term: "seq 開始 [増分] 終了", mean: "連番を出力する（seq 1 2 9 → 1 3 5 7 9）" },
  { id: 2030, sec: "1.06/スクリプトで使う小技（read・seq・exit・終了ステータス）", term: "exit 数値", mean: "スクリプトを終了し、その数値を終了ステータスとして返す" },
  { id: 2031, sec: "1.06/スクリプトで使う小技（read・seq・exit・終了ステータス）", term: "A && B ／ A || B", mean: "A が成功したら B ／ A が失敗したら B" },

  /* ===== 1.07 ネットワークの基本 ===== */
  { id: 2032, sec: "1.07/ネットワークの基本用語", term: "LAN ／ WAN", mean: "建物内などの狭い範囲 ／ 離れた LAN を通信事業者の回線で結ぶ広い範囲" },
  { id: 2033, sec: "1.07/ネットワークの基本用語", term: "帯域幅", mean: "1秒間に送れるデータ量。単位は bps" },
  { id: 2034, sec: "1.07/ネットワークの基本用語", term: "輻輳（ふくそう） ／ ジッタ", mean: "ネットワークの混雑 ／ 到着時間のゆらぎ" },
  { id: 2035, sec: "1.07/トポロジと通信の種類", term: "スター型トポロジ", mean: "ハブを中心に接続。現在の LAN で最も一般的" },
  { id: 2036, sec: "1.07/トポロジと通信の種類", term: "ユニキャスト／ブロードキャスト／マルチキャスト", mean: "1対1 ／ 1対全員 ／ 1対特定のグループ" },
  { id: 2037, sec: "1.07/OSI参照モデル", term: "OSI参照モデル（7層）", mean: "上から アプリケーション・プレゼンテーション・セッション・トランスポート・ネットワーク・データリンク・物理。ISO が策定" },
  { id: 2038, sec: "1.07/OSI参照モデル", term: "ネットワーク層（L3）", mean: "エンドツーエンドの通信と経路選択。論理アドレス（IP）を使う" },
  { id: 2039, sec: "1.07/OSI参照モデル", term: "データリンク層（L2）", mean: "隣接ノード間の通信。物理アドレス（MAC）を使う" },
  { id: 2040, sec: "1.07/TCP/IPとカプセル化", term: "TCP/IP（4層）", mean: "アプリケーション・トランスポート・インターネット・リンク層。仕様は RFC で公開" },
  { id: 2041, sec: "1.07/TCP/IPとカプセル化", term: "カプセル化 ／ 非カプセル化", mean: "送信時に各層でヘッダを付ける ／ 受信時に外す" },
  { id: 2042, sec: "1.07/TCP/IPとカプセル化", term: "セグメント・パケット・フレーム", mean: "トランスポート層（TCP）・ネットワーク層・データリンク層の PDU の呼び名" },
  { id: 2043, sec: "1.07/TCPとUDP", term: "TCP", mean: "コネクション型・信頼性重視。確認応答・再送・順序制御。3ウェイハンドシェイクで接続" },
  { id: 2044, sec: "1.07/TCPとUDP", term: "UDP", mean: "コネクションレス型・速さ重視（ベストエフォート）。DNS・DHCP・NTP・動画配信" },
  { id: 2045, sec: "1.07/TCPとUDP", term: "SYN ／ ACK ／ FIN ／ RST", mean: "TCP の制御ビット：接続要求／確認応答／切断要求／強制切断" },
  { id: 2046, sec: "1.07/IPとICMP", term: "ICMP タイプ 8 ／ 0", mean: "エコー要求 ／ エコー応答（ping が使う）" },
  { id: 2047, sec: "1.07/IPとICMP", term: "ICMP タイプ 3 ／ 11", mean: "宛先到達不能 ／ 時間超過（traceroute が使う）" },
  { id: 2048, sec: "1.07/IPとICMP", term: "TTL", mean: "ルーターを通るたびに1減り、0で破棄される値" },
  { id: 2049, sec: "1.07/IPとICMP", term: "ARP", mean: "IPアドレスから MAC アドレスを調べるプロトコル" },

  /* ===== 1.07 アドレス ===== */
  { id: 2050, sec: "1.07/IPアドレスとサブネット", term: "IPv4", mean: "32ビット。8ビットずつ4つに区切って10進数で書く" },
  { id: 2051, sec: "1.07/IPアドレスとサブネット", term: "/24 ＝ 255.255.255.0", mean: "使えるホスト数は 254（2^8 − 2）" },
  { id: 2052, sec: "1.07/IPアドレスとサブネット", term: "ホスト数の式", mean: "2^(32 − プレフィックス長) − 2（ネットワークアドレスとブロードキャストを除く）" },
  { id: 2053, sec: "1.07/IPアドレスとサブネット", term: "127.0.0.1", mean: "IPv4 のループバックアドレス（localhost）" },
  { id: 2054, sec: "1.07/プライベートIPアドレスとNAT", term: "プライベートIPアドレス", mean: "10.0.0.0/8、172.16.0.0/12（〜172.31）、192.168.0.0/16（RFC1918）" },
  { id: 2055, sec: "1.07/プライベートIPアドレスとNAT", term: "NAT ／ NAPT（IPマスカレード）", mean: "アドレスを変換 ／ ポート番号も使い1つのグローバルアドレスを複数台で共有" },
  { id: 2056, sec: "1.07/IPv6", term: "IPv6", mean: "128ビット。16ビットずつ8つに区切って16進数で書き、0の連続は :: に省略（1か所だけ）" },
  { id: 2057, sec: "1.07/IPv6", term: "::1 ／ fe80::/10", mean: "IPv6 のループバック ／ リンクローカルアドレス" },
  { id: 2058, sec: "1.07/ポート番号（ウェルノウンポート）", term: "20/21・22・23・25", mean: "FTP・SSH・Telnet・SMTP" },
  { id: 2059, sec: "1.07/ポート番号（ウェルノウンポート）", term: "53・80・110・123", mean: "DNS・HTTP・POP3・NTP" },
  { id: 2060, sec: "1.07/ポート番号（ウェルノウンポート）", term: "143・443", mean: "IMAP・HTTPS" },
  { id: 2061, sec: "1.07/ポート番号（ウェルノウンポート）", term: "0〜1023", mean: "ウェルノウンポートの範囲（全体は0〜65535の16ビット）" },
  { id: 2062, sec: "1.07/ポート番号（ウェルノウンポート）", term: "/etc/services", mean: "サービス名とポート番号の対応表" },

  /* ===== 1.07 設定と問題解決 ===== */
  { id: 2063, sec: "1.07/ネットワークの設定ファイルとホスト名", term: "/etc/hosts", mean: "ホスト名と IPアドレスの対応表（DNS を使わない名前解決）" },
  { id: 2064, sec: "1.07/ネットワークの設定ファイルとホスト名", term: "/etc/hostname", mean: "自分のホスト名が書かれたファイル" },
  { id: 2065, sec: "1.07/ネットワークの設定ファイルとホスト名", term: "hostnamectl set-hostname", mean: "ホスト名を恒久的に変更する（systemd）" },
  { id: 2066, sec: "1.07/ネットワーク設定コマンド（nmcli・ip・ifconfig）", term: "nmcli", mean: "NetworkManager を操作する。general／radio／device／connection を対象にする" },
  { id: 2067, sec: "1.07/ネットワーク設定コマンド（nmcli・ip・ifconfig）", term: "nmcli connection show", mean: "接続（コネクション）の一覧。up／down で有効・無効" },
  { id: 2068, sec: "1.07/ネットワーク設定コマンド（nmcli・ip・ifconfig）", term: "ip addr ／ ip link ／ ip route", mean: "IPアドレス ／ インターフェイス ／ ルーティングテーブルの操作" },
  { id: 2069, sec: "1.07/ネットワーク設定コマンド（nmcli・ip・ifconfig）", term: "ifconfig ／ ifup ／ ifdown", mean: "古いインターフェイス設定のコマンド。NetworkManager 環境では非推奨" },
  { id: 2070, sec: "1.07/ネットワークの問題解決", term: "ping -c 回数", mean: "ICMP エコーで応答を確認。-c が無いと Ctrl+C まで続く" },
  { id: 2071, sec: "1.07/ネットワークの問題解決", term: "traceroute ／ tracepath", mean: "宛先までに経由するルーターを表示する" },
  { id: 2072, sec: "1.07/ネットワークの問題解決", term: "ss -antp", mean: "すべての TCP ソケットを数値で、プロセスと一緒に表示（netstat の後継）" },
  { id: 2073, sec: "1.07/ネットワークの問題解決", term: "nc（netcat）", mean: "ホスト・ポートとデータをやりとりする。-l で待ち受け、-u で UDP" },
  { id: 2074, sec: "1.07/ルーティング", term: "route -n ／ ip route show ／ netstat -r", mean: "ルーティングテーブルを表示する" },
  { id: 2075, sec: "1.07/ルーティング", term: "route add default gw ⇔ ip route add default via", mean: "デフォルトゲートウェイの設定（gw と via の違い）" },
  { id: 2076, sec: "1.07/クライアント側のDNS設定", term: "/etc/resolv.conf", mean: "問い合わせる DNS サーバー（nameserver）を書く" },
  { id: 2077, sec: "1.07/クライアント側のDNS設定", term: "/etc/nsswitch.conf", mean: "名前解決の順番（hosts: files dns）を書く" },
  { id: 2078, sec: "1.07/クライアント側のDNS設定", term: "正引き ／ 逆引き", mean: "ホスト名 → IPアドレス ／ IPアドレス → ホスト名" },
  { id: 2079, sec: "1.07/クライアント側のDNS設定", term: "dig -x IPアドレス", mean: "逆引きする。dig @サーバー 名前 タイプ で問い合わせ先と種類を指定" },
  { id: 2080, sec: "1.07/クライアント側のDNS設定", term: "getent hosts 名前", mean: "nsswitch.conf の順で /etc/hosts も含めて名前解決する" },
  { id: 2081, sec: "1.07/クライアント側のDNS設定", term: "A ／ AAAA ／ MX ／ NS", mean: "IPv4 ／ IPv6 ／ メールサーバー ／ DNSサーバー のレコード" },

  /* ===== 1.08 アカウント ===== */
  { id: 2082, sec: "1.08/ユーザーとグループ", term: "プライマリグループ ／ サブグループ", mean: "必ず1つ属する基本のグループ ／ それ以外に所属するグループ" },
  { id: 2083, sec: "1.08/ユーザーとグループ", term: "id ユーザー", mean: "UID・GID・所属グループを表示する" },
  { id: 2084, sec: "1.08/アカウント情報のファイル（passwd・shadow・group）", term: "/etc/passwd", mean: "名前:x:UID:GID:コメント:ホーム:シェル の7項目。誰でも読める" },
  { id: 2085, sec: "1.08/アカウント情報のファイル（passwd・shadow・group）", term: "/etc/shadow", mean: "暗号化パスワードと有効期限。root だけが読める" },
  { id: 2086, sec: "1.08/アカウント情報のファイル（passwd・shadow・group）", term: "/etc/group", mean: "グループ名:x:GID:メンバー の4項目" },
  { id: 2087, sec: "1.08/アカウント情報のファイル（passwd・shadow・group）", term: "/etc/skel", mean: "新規ユーザーのホームにコピーされるひな形" },
  { id: 2088, sec: "1.08/ユーザー・グループ管理コマンド", term: "useradd -m", mean: "ホームディレクトリも作成してユーザーを追加する" },
  { id: 2089, sec: "1.08/ユーザー・グループ管理コマンド", term: "useradd -g ／ -G", mean: "プライマリグループ ／ サブグループを指定" },
  { id: 2090, sec: "1.08/ユーザー・グループ管理コマンド", term: "usermod -aG グループ", mean: "今のサブグループを残したまま追加（-a が無いと置き換え）" },
  { id: 2091, sec: "1.08/ユーザー・グループ管理コマンド", term: "usermod -L ／ -U", mean: "パスワードをロック ／ ロック解除" },
  { id: 2092, sec: "1.08/ユーザー・グループ管理コマンド", term: "userdel -r", mean: "ホームディレクトリも含めてユーザーを削除" },
  { id: 2093, sec: "1.08/ユーザー・グループ管理コマンド", term: "groupmod -n 新名 旧名", mean: "グループ名を変更（-g は GID の変更）" },
  { id: 2094, sec: "1.08/ユーザー・グループ管理コマンド", term: "passwd -l ／ -u", mean: "パスワードをロック ／ ロック解除" },

  /* ===== 1.08 ジョブとロケール ===== */
  { id: 2095, sec: "1.08/ジョブスケジューリング（cron）", term: "分 時 日 月 曜日 コマンド", mean: "crontab の書式。分0〜59・時0〜23・曜日0〜7（0と7が日曜）" },
  { id: 2096, sec: "1.08/ジョブスケジューリング（cron）", term: "crontab -e ／ -l ／ -r", mean: "編集 ／ 一覧 ／ すべて削除" },
  { id: 2097, sec: "1.08/ジョブスケジューリング（cron）", term: "/etc/crontab", mean: "システム用の crontab。ユーザー名の欄がある" },
  { id: 2098, sec: "1.08/ジョブスケジューリング（cron）", term: "/etc/cron.allow ／ cron.deny", mean: "使えるユーザー ／ 使えないユーザー。allow があればそれが優先" },
  { id: 2099, sec: "1.08/ジョブスケジューリング（cron）", term: "*/15", mean: "15ごと（分の欄なら15分ごと）" },
  { id: 2100, sec: "1.08/at と anacron", term: "at ／ atq ／ atrm", mean: "1回だけ予約 ／ 予約の一覧 ／ 予約の削除" },
  { id: 2101, sec: "1.08/at と anacron", term: "anacron（/etc/anacrontab）", mean: "電源が切れていて実行し損ねた定期ジョブを起動後に実行する" },
  { id: 2102, sec: "1.08/ローカライゼーションと国際化", term: "i18n ／ L10n", mean: "国際化（多言語に対応できる作り）／ 地域化（特定の地域に合わせる）" },
  { id: 2103, sec: "1.08/ローカライゼーションと国際化", term: "LC_ALL ＞ LC_* ＞ LANG", mean: "ロケールの環境変数の優先順位" },
  { id: 2104, sec: "1.08/ローカライゼーションと国際化", term: "locale -a", mean: "使えるロケールの一覧" },
  { id: 2105, sec: "1.08/ローカライゼーションと国際化", term: "LANG=C コマンド", mean: "そのコマンドだけ英語の標準形式で動かす（エラー検索・スクリプト向け）" },
  { id: 2106, sec: "1.08/文字コードと iconv", term: "iconv -f 元 -t 先", mean: "文字コードを変換する（from ／ to）" },
  { id: 2107, sec: "1.08/文字コードと iconv", term: "ASCII ／ UTF-8", mean: "7ビット128文字 ／ Unicode を1〜4バイトで表す現在の主流" },
  { id: 2108, sec: "1.08/文字コードと iconv", term: "Shift_JIS ／ EUC-JP ／ ISO-2022-JP", mean: "Windows ／ UNIX系 ／ 電子メールで使われてきた日本語" },

  /* ===== 1.09 時刻 ===== */
  { id: 2109, sec: "1.09/システムクロックとハードウェアクロック", term: "システムクロック ／ ハードウェアクロック", mean: "カーネルが管理し電源で消える ／ マザーボードの時計で消えない" },
  { id: 2110, sec: "1.09/システムクロックとハードウェアクロック", term: "hwclock -w（--systohc）", mean: "システム → ハードウェアクロックへ書き込む" },
  { id: 2111, sec: "1.09/システムクロックとハードウェアクロック", term: "hwclock -s（--hctosys）", mean: "ハードウェア → システムクロックへ読み込む" },
  { id: 2112, sec: "1.09/タイムゾーン", term: "/etc/localtime", mean: "システムのタイムゾーン（/usr/share/zoneinfo のコピーかリンク）" },
  { id: 2113, sec: "1.09/タイムゾーン", term: "timedatectl set-timezone", mean: "タイムゾーンを設定する（set-ntp yes で NTP 同期）" },
  { id: 2114, sec: "1.09/タイムゾーン", term: "TZ", mean: "ユーザー・コマンドごとにタイムゾーンを変える環境変数" },
  { id: 2115, sec: "1.09/NTP と chrony", term: "NTP（UDP 123）", mean: "ネットワークで時刻を同期する。Stratum の数字が小さいほど基準に近い" },
  { id: 2116, sec: "1.09/NTP と chrony", term: "chronyd ／ chronyc sources", mean: "chrony のデーモン（/etc/chrony.conf）／ 参照先の一覧表示" },
  { id: 2117, sec: "1.09/NTP と chrony", term: "ntpd ／ ntpdate", mean: "常に同期するデーモン（/etc/ntp.conf）／ 一度だけ合わせる" },

  /* ===== 1.09 ログとメール ===== */
  { id: 2118, sec: "1.09/システムログ（rsyslog）", term: "ファシリティ.プライオリティ 出力先", mean: "/etc/rsyslog.conf のルールの書式" },
  { id: 2119, sec: "1.09/システムログ（rsyslog）", term: "emerg・alert・crit・err・warning・notice・info・debug", mean: "プライオリティ（重要度の高い順）" },
  { id: 2120, sec: "1.09/システムログ（rsyslog）", term: "mail.info ⇔ mail.=info", mean: "info 以上 ⇔ info だけ" },
  { id: 2121, sec: "1.09/システムログ（rsyslog）", term: "@host ／ @@host", mean: "UDP で転送 ／ TCP で転送" },
  { id: 2122, sec: "1.09/システムログ（rsyslog）", term: "logger -p 施設.重要度 \"文\"", mean: "ログを手動で送る（テスト用）" },
  { id: 2123, sec: "1.09/システムログ（rsyslog）", term: "imudp ／ imtcp", mean: "他のホストからログを受け取る rsyslog のモジュール" },
  { id: 2124, sec: "1.09/systemd-journald と journalctl", term: "journalctl -u ／ -b ／ -f ／ -p", mean: "ユニット指定 ／ 今回の起動以降 ／ 追いかけ ／ 重要度で絞る" },
  { id: 2125, sec: "1.09/systemd-journald と journalctl", term: "/var/log/journal", mean: "作るとジャーナルが永続保存される（既定は /run/log/journal で再起動で消える）" },
  { id: 2126, sec: "1.09/ログローテーション", term: "/etc/logrotate.conf", mean: "ログローテーションの全体設定（個別は /etc/logrotate.d/）" },
  { id: 2127, sec: "1.09/ログローテーション", term: "rotate ／ compress ／ create", mean: "残す世代数 ／ gzip で圧縮 ／ 新しいログファイルを作る" },
  { id: 2128, sec: "1.09/メールの仕組みとMTA", term: "MUA ／ MTA ／ MDA", mean: "メールを読み書き ／ サーバー間で転送 ／ メールボックスへ配達" },
  { id: 2129, sec: "1.09/メールの仕組みとMTA", term: "postfix ／ exim", mean: "代表的な MTA（postfix は sendmail 互換、exim は Debian 系で標準）" },
  { id: 2130, sec: "1.09/メールの仕組みとMTA", term: "/etc/aliases → newaliases", mean: "システムのメール転送設定と、その反映コマンド" },
  { id: 2131, sec: "1.09/メールの仕組みとMTA", term: "~/.forward ／ mailq", mean: "個人のメール転送先 ／ 送信待ちキューの表示" },

  /* ===== 1.10 セキュリティ ===== */
  { id: 2132, sec: "1.10/ローカルセキュリティの管理", term: "find / -perm -u+s", mean: "SUID の付いたファイルを探す（-g+s で SGID）" },
  { id: 2133, sec: "1.10/パスワードの有効期限（chage）", term: "chage -l ／ -M ／ -E", mean: "期限の表示 ／ 最長有効日数 ／ アカウントの失効日" },
  { id: 2134, sec: "1.10/開いているポートの確認", term: "nmap", mean: "外から開いているポートを調べる（ポートスキャン）" },
  { id: 2135, sec: "1.10/開いているポートの確認", term: "lsof -i ／ fuser -n tcp 番号", mean: "ネットワークを開いているプロセス ／ そのポートを使う PID" },
  { id: 2136, sec: "1.10/ログイン状況の確認", term: "who ／ w ／ last", mean: "ログイン中 ／ ログイン中と実行内容 ／ ログイン履歴（/var/log/wtmp）" },
  { id: 2137, sec: "1.10/リソース制限（ulimit）", term: "ulimit -a ／ -u ／ -n", mean: "制限の一覧 ／ プロセス数 ／ 開けるファイル数" },
  { id: 2138, sec: "1.10/su と sudo", term: "su ⇔ sudo", mean: "切り替え先（root）のパスワード ⇔ 自分のパスワードで許可されたコマンドだけ" },
  { id: 2139, sec: "1.10/su と sudo", term: "su -", mean: "ログインシェルとして root に切り替える（root の環境になる）" },
  { id: 2140, sec: "1.10/su と sudo", term: "visudo", mean: "/etc/sudoers を文法チェック付きで編集する" },
  { id: 2141, sec: "1.10/su と sudo", term: "NOPASSWD:", mean: "sudoers でパスワードを聞かずに実行させる指定" },
  { id: 2142, sec: "1.10/自動ログアウトとログインの禁止", term: "TMOUT", mean: "操作が無いまま指定秒数たつと自動ログアウト" },
  { id: 2143, sec: "1.10/自動ログアウトとログインの禁止", term: "/etc/nologin", mean: "存在すると root 以外はログインできない" },
  { id: 2144, sec: "1.10/不要なサービスの停止", term: "systemctl stop ⇔ disable", mean: "今止める ⇔ 次回起動から自動起動しない" },
  { id: 2145, sec: "1.10/不要なサービスの停止", term: "inetd ／ xinetd", mean: "要求があったときだけサービスを起動するスーパーサーバー" },
  { id: 2146, sec: "1.10/ファイアウォール", term: "firewalld（firewall-cmd）／ iptables", mean: "ゾーン単位で設定 ／ チェインにルールを並べる。実体はカーネルの netfilter" },
  { id: 2147, sec: "1.10/SSHと公開鍵認証", term: "ssh-keygen", mean: "SSH の鍵ペアを作る（-t ed25519 など）" },
  { id: 2148, sec: "1.10/SSHと公開鍵認証", term: "~/.ssh/authorized_keys", mean: "ログイン先に置く、ログインを許可する公開鍵の一覧" },
  { id: 2149, sec: "1.10/SSHと公開鍵認証", term: "~/.ssh/known_hosts", mean: "接続したサーバーのホスト鍵の記録" },
  { id: 2150, sec: "1.10/SSHと公開鍵認証", term: "ssh-agent ／ ssh-add", mean: "秘密鍵を預かる常駐プログラム ／ そこへ秘密鍵を登録" },
  { id: 2151, sec: "1.10/SSHと公開鍵認証", term: "scp 元 先", mean: "SSH でファイルをコピー（リモートは ホスト:パス、-r でディレクトリ）" },
  { id: 2152, sec: "1.10/GnuPGによる暗号化", term: "gpg -e -r 相手 ／ gpg -d", mean: "相手の公開鍵で暗号化 ／ 自分の秘密鍵で復号" },
  { id: 2153, sec: "1.10/クラウドセキュリティ", term: "多要素認証（MFA）", mean: "管理コンソールへのログインに、パスワード以外の要素も使う" },
  { id: 2154, sec: "1.10/クラウドセキュリティ", term: "リージョン", mean: "データセンターがある地域" },
  { id: 2155, sec: "1.10/クラウドセキュリティ", term: "責任共有モデル", mean: "物理設備は事業者、OS の設定・データは利用者が守る" },

  /* ===== 1.11 オープンソース ===== */
  { id: 2156, sec: "1.11/オープンソースとは", term: "オープンソース", mean: "ソース公開・改変・再配布が自由。著作権は放棄されていない" },
  { id: 2157, sec: "1.11/オープンソースとは", term: "FOSS ／ FLOSS", mean: "フリーソフトウェアとオープンソースソフトウェアをまとめた呼び名" },
  { id: 2158, sec: "1.11/オープンソースとは", term: "プロプライエタリ", mean: "企業などが権利を持つ商用ソフトウェア。改変・再配布は制限される" },
  { id: 2159, sec: "1.11/オープンソースライセンス", term: "コピーレフト", mean: "派生物にも同じライセンスを引き継がせ、ソース公開を求める考え方（GPL）" },
  { id: 2160, sec: "1.11/オープンソースライセンス", term: "GPL ／ LGPL ／ AGPL", mean: "改変版もソース公開 ／ リンクだけなら公開不要 ／ ネット越しの利用でも公開" },
  { id: 2161, sec: "1.11/オープンソースライセンス", term: "BSD ／ MIT ／ Apache 2.0", mean: "コピーレフトでないライセンス（ソース公開不要）。Apache は特許の許諾付き" },
  { id: 2162, sec: "1.11/オープンソースライセンス", term: "MPL", mean: "Mozilla。改変した MPL のファイルは公開、組み合わせた自分のファイルは公開不要" },
  { id: 2163, sec: "1.11/オープンソースの開発とコミュニティ", term: "Git", mean: "分散型のバージョン管理システム。Linux カーネル開発のために作られた" },
  { id: 2164, sec: "1.11/オープンソースの開発とコミュニティ", term: "メジャー.マイナー.リリース", mean: "バージョン番号の並び（3.15.4 なら 3 がメジャー）" },

  /* ===== 直前チェック（102） ===== */
  { id: 2165, sec: "102/混同しやすいペア（102）", term: "hwclock -w ⇔ -s", mean: "システム → ハード（systohc）⇔ ハード → システム（hctosys）" },
  { id: 2166, sec: "102/混同しやすいペア（102）", term: "bash script ⇔ source script", mean: "子プロセスで実行 ⇔ 今のシェルで実行（変数が残る）" },
  { id: 2167, sec: "102/混同しやすいペア（102）", term: "-eq ⇔ =", mean: "数値が等しい ⇔ 文字列が等しい" },
  { id: 2168, sec: "102/混同しやすいペア（102）", term: "dig・host ⇔ getent", mean: "DNS だけに問い合わせる ⇔ /etc/hosts も含めて引く" }

]);
